### ISSUE TITLE
Mi Carousel error

### ISSUE THREAD

**Issue by samdhu** [you-apps/WallYou#116]
### Steps to reproduce

![Screenshot_20230811-215957](https://github.com/you-apps/WallYou/assets/36665232/1a361d02-340d-4e2a-ab65-fbdc5e0939f3)

### Expected behavior

Always happened when i open the mi corousel section 

### Actual behavior

It happened on v 3.0 too and still on v 5.0 i dont know why

### Wall You version

3.0 - 5.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It seems like there were breaking API changes from Xiaomi's side. I'll remove the engine for now.
