### ISSUE TITLE
Small feature requests (7 listed)

### ISSUE THREAD

**Issue by Zeeex** [you-apps/WallYou#118]
### Describe your suggested feature

Thanks for this beautiful app. Hopeful this list won't trouble you much 😅

As with the "small bugs reports". Didn't feel the need (but feel free to correct me) for multiple tickets.

1. Introduce a feature to allow excluding specific tags (I'm aware this functionality is supported by "Wallhaven," uncertain about other services). However, not sure if you need to be logged in for this.

2. Related to (1), retrieve a user's tags block list with or without an account?
Wallhaven example below:
![image](https://github.com/you-apps/WallYou/assets/16362320/2e954a84-ca1f-4971-aa5c-59c46bcf709b)

3. Related to (1) (2), can you add an option to login with your account on Wallhaven, and possibly other services? I'm uncertain this belongs in this app, as I'm hesitant to bloat it.

4. Upon opening an image, would be nice if we could hide (at least temporarily) the action bar to view the full picture. My suggestion would be a long press on the image (like Instagram does), or/and when zooming in on it.

5. I'm assuming that when an image is accessed, the color palette of the image appears at the bottom? Would be nice to deactivate this feature, and also to have some guide for users unfamiliar with it.

6. While viewing an image, implementing tooltips when performing a long press on action items at the bottom could be a beneficial.
7. When attempting to apply a blur effect to an image, it would be preferable if the overlay didn't become darker. Additionally, it would be appreciated if the background action bar could be hidden. Moreover, reducing the height of the current popup to provide a clearer preview of the blurring effect would be beneficial, similar to how brightness adjustments work on Android.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'll have a deeper look into some issues when my time allows me to, but I can already spoiler you concerning 3:
* Support for logging in to any services is not planned at Wall You, the goal is to make the user experience as good as possible, the same for everyone, without needing to use accounts at services that might not be really privacy-respecting.

Otherwise, there are some valid points in the suggestions, but I'll be more specific once I have time to work on some of them as well.

**Comment by Bnyro** [comment]
For 2., you should already be able to do that by add a `-` in front of the tag name, e.g. `-anime`. See #18 for reference.

**Comment by Bnyro** [comment]
7. is not possible unfortunately, since native Android dialogs don't support that.

**Comment by Bnyro** [comment]
4, 5, 6 are implemented now - the other ones were rejected with reasoning above.
