### ISSUE TITLE
Mi Carousel option seems to be broken

### ISSUE THREAD

**Issue by ThePlayer14** [you-apps/WallYou#124]
### Steps to reproduce

Greetings!
Upon selecting the Mi Carousel option, the app displays a toast message and doesn't load any images at all.
This is the toast popup, from NiceCatch:
![image](https://github.com/you-apps/WallYou/assets/24374531/fc1bf770-3e87-443f-be80-c5baf04ab599)

### Expected behavior

The app should load images from Mi Carousel source 

### Actual behavior

The app fails to load the Mi Carousel source

### Wall You version

5.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #116
