### ISSUE TITLE
Local files only option / disable APIs and network access

### ISSUE THREAD

**Issue by jamesrbarker** [you-apps/WallYou#125]
### Describe your suggested feature

Thank you for making this app!  It has saved me after my previous wallpaper-changing app stopped working.

May I request a feature?
I synchronize a wallpaper directory between my phone and laptop.  I do not use any of the online wallpaper providers.  I'm glad to see that WallYou allows using a local folder as the wallpaper source.

May I request a toggle in the Settings to disable WallYou's network access?

Best regards, and thank you again!
J

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can restrict the apps network access either via "NetGuard" (F-Droid) or on new Android versions in the data usage settings.

Wall You is meant to be used for online sources primarily, hence I don't think this is reasonable to add.
