### ISSUE TITLE
Ability to view wallpaper license

### ISSUE THREAD

**Issue by Artem13327** [you-apps/WallYou#126]
### Describe your suggested feature

For example, add a link to the license in the wallpaper information menu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, only Unsplash returns a license in the API request, which is always set to "Unsplash license" however. Thus it doesn't make sense to add this.
