### ISSUE TITLE
Ability to hide sources

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [you-apps/WallYou#130]
### Describe your suggested feature

I only use Wallhaven so I'm wondering if a feature where hiding unwanted sources could be considered?

Isn't Xiaomi considered to be spying? My network security blocks it completely.

### Other details

Feature: Ability to show/hide available wallpaper sources displayed in side panel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned. If you don't wanna use them, just don't click them.

Mi Carousel already has been removed some versions ago...

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
That's strange, on F-Droid the latest is 4.1 (14/7/2023).

**Comment by Bnyro** [comment]
No, the latest version on F-Droid is 6.0, see https://f-droid.org/en/packages/com.bnyro.wallpaper/.
