### ISSUE TITLE
Filter by name/labels

### ISSUE THREAD

**Issue by inson1** [you-apps/WallYou#135]
### Describe your suggested feature

On top right side would be search icon.
And then user could filter by the name/labels.
Idk If the apis do have names/labels for wallpapers.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by inson1** [comment]
And sorry for not adding it to disscusion. I created this issue first and then did I find out about it.

**Comment by Bnyro** [comment]
Unfortunately, only few APIs support it and it would be very difficult to implmenet for all of them at the current state.
