### ISSUE TITLE
Lemmy source Error

### ISSUE THREAD

**Issue by inson1** [you-apps/WallYou#136]
### Steps to reproduce

I clicked on menu and then on Lemmy source.

### Expected behavior

Open the source with wallpapers

### Actual behavior

Error toast showed up.

![Screenshot_2023-10-09-04-50-22-886_com.bnyro.wallpaper.jpg](https://github.com/you-apps/WallYou/assets/75314629/93fab311-4eb4-43fe-a1e6-7cc2ac1521f6)

![Screenshot_2023-10-09-05-56-28-426_com.bnyro.wallpaper.jpg](https://github.com/you-apps/WallYou/assets/75314629/52a939e6-d830-4308-9018-02cb31a5a1e0)

### Wall You version

6.0

### Android version

Android 11 MIUI 12.5.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
fixed in https://github.com/you-apps/WallYou/commit/fb3e04630342e64a5569f6894f669c8f310c7f1a
