### ISSUE TITLE
Create Github actions

### ISSUE THREAD

**Issue by Jean-BaptisteC** [you-apps/WallYou#137]
### Describe your suggested feature

Like other projects of you apps, I suggest to add CI to build new PR create by community.

### Other details

I have already developed CI to build debug app and build release app for Exodus Privacy android app
https://github.com/Exodus-Privacy/exodus-android-app/blob/master/.github/workflows/main.yml
https://github.com/Exodus-Privacy/exodus-android-app/blob/master/.github/workflows/release.yml

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems like a good idea, feel free to open a PR :+1:
