### ISSUE TITLE
Unable to Use Local Directories

### ISSUE THREAD

**Issue by r-tgh** [you-apps/WallYou#141]
### Steps to reproduce

1. uncheck **_Combined wallpaper changer_** option
2. change **_Wallpaper changer source_** for **_Home Screen_** to **_Local_**
3. select required device folder
4. click on **_Allow_** when prompted with the access permission request
5. repeat step 2-3-4 for **_Lock Screen_**

### Expected behavior

1. the respective folders for both, Home and Lock, screens should get selected and reflect correctly in the app settings
2. the device wallpapers should reflect the change as per selected images

### Actual behavior

1. the folders are not getting selected even after allowing access or testing with different folders; app setting still shows the button to **_Choose directory_**
2. the wallpapers are not from the selected device folders either; they remain chosen from whichever Online collection was selected prior to the source being changed to Local

### Wall You version

6.0

### Android version

Android 13

### Other details

- installed app via the latest APK available on the GitHub repository
- device used is Samsung S23 Ultra
- tried checking the app permissions phone setting as well since Files permissions might have been disabled
    - no additional app permissions were required/allowed
    - the default permissions did not list system files

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. added in https://github.com/you-apps/WallYou/commit/41d060f5c31223c8f9f7d1b71222351c6c5109ec

**Comment by r-tgh** [comment]
ah, i see the folder name display was not an existing feature, my bad. it definitely helps with confirming whether the selection was made correctly, so thank you for handling suitably.

i understand that the second issue regarding the app not working properly has been referenced to another open issue, i will keep up to date with the same accordingly.

thanks! (:
