### ISSUE TITLE
2 suggestions for auto wallpaper changer

### ISSUE THREAD

**Issue by AshesHub1** [you-apps/WallYou#147]
### Describe your suggested feature

Add favorites to the list of sources 
And a option to to turn off the auto wallpaper changer per locked screen and home screen to the sources

I love the app it would be nice if you could add these 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Both things are already possible.
