### ISSUE TITLE
Info panel improvements and tags

### ISSUE THREAD

**Issue by piostaet** [you-apps/WallYou#149]
### Describe your suggested feature

a few ideas:
- show the tags for a selected image, for example in the info panel
- make the URL in the info panel selectable or clickable, so the link is actually usable
- in a possible tag overview, copy tags or make a search for images with similar tags

overall already a really nice app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As far as I know none of the supported engines supports tags, so that won't be possible.

> make the URL in the info panel selectable or clickable, so the link is actually usable
>
https://github.com/you-apps/WallYou/commit/ff057e11ccfd537b3ee3de5139a5c0273c5cfcfe
