### ISSUE TITLE
Add source filters to auto background changer

### ISSUE THREAD

**Issue by JojoBr0** [you-apps/WallYou#151]
### Describe your suggested feature

It would be great if the pictures from the auto background changer could be filter in the same way as these you can check in app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already the case.
