### ISSUE TITLE
Option to change wallpaper on every unlock

### ISSUE THREAD

**Issue by v0idspace** [you-apps/WallYou#154]
### Describe your suggested feature

Another option in the Change interval menu , called every screen unlock or something similar that runs the update wallpapers circle everytime the device  unlocks instead of the some x minutes  

### Other details

This feature idea is from the mi wallpaper carousel app, Sadly that library is no longer supported in this  app , 😭 (cries in stock Android)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The app would need to consistently run as a foreground service for that, which would probably use a lot of resources for nothing.

**Comment by Bnyro** [comment]
Opinions @M00NJ @SuhasDissa ?

**Comment by SuhasDissa** [comment]
> Opinions @M00NJ @SuhasDissa ?

Maybe we could use a Broadcast Receiver with some action like [`ACTION_USER_PRESENT`](https://developer.android.com/reference/android/content/Intent#ACTION_USER_PRESENT) or [`ACTION_SCREEN_ON`](https://developer.android.com/reference/android/content/Intent#ACTION_SCREEN_ON)

**Comment by Bnyro** [comment]
> Maybe we could use a Broadcast Receiver with some action like [`ACTION_USER_PRESENT`](https://developer.android.com/reference/android/content/Intent#ACTION_USER_PRESENT) or [`ACTION_SCREEN_ON`](https://developer.android.com/reference/android/content/Intent#ACTION_SCREEN_ON)
>
They can't be added to `AndroidManifest.xml`, they can only be registered at the app's runtime. That's the point.

**Comment by M00NJ** [comment]
I don't know a way to make this possible in the background. It sounds like a nice feature, but if it's only possible with foreground service then I wouldn't add it.
