### ISSUE TITLE
Long press menu for quickly accessing actions on wallpaper items

### ISSUE THREAD

**Issue by luckkmaxx** [you-apps/WallYou#158]
### Describe your suggested feature

You could change the favorites fab to some desired action (set, download, info or favorite).
Also could be smart to set an action when long pressing a thumbnail

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Decided against this now.

> You could change the favorites fab to some desired action (set, download, info or favorite).
>
I think that too much configuration options like that would make the settings just more complicated, and I don't think many people want to use different quick actions.

> Also could be smart to set an action when long pressing a thumbnail
>
That would only save you one single click and hence I don't think it's worth it.
