### ISSUE TITLE
Add an option to have separate wallpapers for dark and light themes

### ISSUE THREAD

**Issue by srfsh** [you-apps/WallYou#161]
### Describe your suggested feature

I love having different wallpapers every once in a while.  During the day, I can use any wallpaper from my favorites.  But the thing is, during evening, night, or in low-light environments in general, some wallpapers are too bright for an eye.  For this very reason, it would be great to have a separate wallpaper collections for dark and light themes of the devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's now possible to automatically invert wallpapers to match the theme (light/dark), see https://github.com/you-apps/WallYou/commit/135ebc5fce5e15e10bc6fa9bb43e19ae2920e6a2. Adding separate wallpaper catalogues for light/dark themes is not planned.
