### ISSUE TITLE
2 Requests on automatic wallpaper change

### ISSUE THREAD

**Issue by beast-14** [you-apps/WallYou#163]
### Describe your suggested feature

1. I request you to introduce a toggle which enables or disables the randomisation of wallpapers for all online, fav, and local.
2. Different timers for lock screen and homescreen wallpaper change.

### Other details

This way same wallpaper won't come again and again because of randomisation and we will have the opportunity to experience the complete folder simultaneously which we have created.

In Android 14 if the lockscreen wallpaper change it also changes the monet color, I like this feature but I want my lockscreen to not change more frequently but I want my homescreen with less timer so I request you to introduce different timers for homescreen and lockscreen wallpapers.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by contact-maximux** [comment]
please remember crop and contrast setting for auto wallpaper changer

**Comment by Bnyro** [comment]
1. not planned as it would require the app to keep track of the recently applied wallpapers and not even all engines have non-random lists
2. resolved by https://github.com/you-apps/WallYou/commit/73d4ba24f951b8d4075e3f198846db99aa624736
