### ISSUE TITLE
Some cropping options

### ISSUE THREAD

**Issue by beast-14** [you-apps/WallYou#164]
### Describe your suggested feature

I would like you to introduce crop, stretch, fit, centre options for wallpaper, I request you .. 

### Other details

Thankyou

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ViktorKahu** [comment]
+1

**Comment by ViktorKahu** [comment]
For a bit of context, currently, when non-standard size or landscape local images are used for the lock screen (not multiple screens like on the home screens), it defaults to selecting the top left corner of the image.

If the image has been cropped or edited, sometimes it will stretch the image.

Now, most landscape photos have the important people/context in the centre, rather in the top left corner. Logic would dictate, that when cropping that image for the wallpaper, the default method (or at the very least, an option) should be center (not top left).

Many thanks.

**Comment by ViktorKahu** [comment]
For the home screen, when multiple screens/scroll are involved, a more complex version of the above should apply. For example, if the user gas two screens, it should centre the image between them (not start top left). If 3, the image should be centered on the 2nd, etc...
