### ISSUE TITLE
Bing wallpaper auto-changer often have black area at bottom.

### ISSUE THREAD

**Issue by UlyssesZh** [you-apps/WallYou#165]
### Steps to reproduce

Set Bing as the auto-changer source.

### Expected behavior

Changes to full wallpapers.

### Actual behavior

![Screenshot_20240101-193351_Niagara Launcher](https://github.com/you-apps/WallYou/assets/26196187/9b3fc076-0bb4-4421-94d2-71737617ff88)

### Wall You version

6.2

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on my end, you should try different image resize modes (from the edit dialog for wallpapers.)
