### ISSUE TITLE
Add option to only change Lockscreen/Main screen

### ISSUE THREAD

**Issue by MaKraMc** [you-apps/WallYou#166]
### Describe your suggested feature

I want to use Wall Man to periodically set my lock screen wallpaper but keep my Home screen as a live background (Managed by another app).
This seems almost possible using the automatic wallpaper changer, however I also need to set a data source for my main screen. I think adding a button like "None" or "don't change" to the data sources or a tick to enable/disable a certain screen would be a good idea.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already added in recent commits.
