### ISSUE TITLE
Multi subreddits

### ISSUE THREAD

**Issue by walrus543** [you-apps/WallYou#169]
### Describe your suggested feature

Hello,
Could you please allow several subreddits as the source of Reddit?
Thank you very much. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, we don't have any plans for that.
