### ISSUE TITLE
Wallpaper not scrolling when switching home screens

### ISSUE THREAD

**Issue by ViktorKahu** [you-apps/WallYou#175]
### Steps to reproduce

1) set a homescreen wallpaper that is larger than the size of the screen.

2) Switch to the next homescreen page to the left or right.

### Expected behavior

Wallpaper should scroll with the screens.

### Actual behavior

Still image.

### Wall You version

7.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by oniGino** [comment]
same issue on pixel 8 w/ grapheneOS v14
