### ISSUE TITLE
No resize mode option.

### ISSUE THREAD

**Issue by ViktorKahu** [you-apps/WallYou#176]
### Steps to reproduce

From #175:

- "The resize mode has to be set to "none".".

### Expected behavior

To be able to set the risize mode to "none"

### Actual behavior

There is no such option anywhere, hence there is no way to fix #175.

### Wall You version

7

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Open an image, click the moon icon.

**Comment by ViktorKahu** [comment]
> Open an image, click the moon icon.

There is no way to do that if using local images. All I can do is select a folder for the home and the lock screen.

IMHO This option should really be in the settings and not for individual images. Or at least a working solution that you see fit for locally stored images.
