### ISSUE TITLE
Version 7.0 seems to have removed the option for setting the wallpaper as spread out & scroll-able across multiple home screens

### ISSUE THREAD

**Issue by JJwA7VR8** [you-apps/WallYou#179]
### Steps to reproduce

Set a wallpaper from any selection available on the app. 

Before version 7.0 of WallYou, one had the option in settings, to set the wallpaper as is or crop it. Before ver. 7.0, the crop option seemed to be bugged (it warped the image), but the default option behaved the way normal Android wallpaper setting does, with the wallpaper spread out across multiple home screens and scroll-able.

### Expected behavior

There should be a setting in the app for setting the wallpaper as 
a) Centered / cropped
b) Spread / default

Option a) should exhibit the current behavior as of ver.  7.0 whereby the wallpaper is correctly cropped/ centered/ scaled on the screen and is the same across multiple home screens

Option b) should exhibit the default non-cropped behavior from the WallYou versions before ver. 7.0. i.e. Set the wallpaper so that it is spread out across multiple screens (depending on dimensions), and scrolling the screens scrolls across the breadth of the wallpaper.

### Actual behavior

The latest version 7.0 does not have these settings. There is only one way of setting the wallpaper, and that is centered / cropped (identical across all screens and not scrollable)

### Wall You version

7.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Open a wallpaper within the app, press the moon icon and select a different resize option ("None" in your case).

**Comment by JJwA7VR8** [comment]
Thanks! Missed that because the crop option used to be in Settings earlier so I assumed it would be a universal option there. This is even better as it can be set per image.
