### ISSUE TITLE
Auto changer limited number of item and non random

### ISSUE THREAD

**Issue by Devoxer** [you-apps/WallYou#183]
### Describe your suggested feature

Thanks for your efforts, I compiled the latest version from source
1. The auto changer cycles through 20 to 40 items from the lebel selected in unsplash and repeat them
2. They always appear in the same order 
3. It will be nice if we have on wifi only toggle and have a buffer when we are in data (it consumed 1.5 gb from my data xD)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. That's related to how Unsplash handles random wallpapers (might be based on your IP)
2. same as above
