### ISSUE TITLE
Wallpaper changer issue

### ISSUE THREAD

**Issue by amijafi** [you-apps/WallYou#184]
### Steps to reproduce

Trying to set some another source rather than default wallhaven

### Expected behavior

I choose some another sources for online wallpaper changer and i ecpect it to set and remember this settings

### Actual behavior

The source reverts back to only wallhaven after some time

### Wall You version

7.0(24)

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by amijafi** [comment]
Again source for wallpaper always revert back to wallhaven , version 8.0

**Comment by MeuhMeuh62** [comment]
Yup same bug for me! Idk how it cannot ne saved or idk but yes.

**Comment by ViktorKahu** [comment]
The problem goes further, any settings are unable to be saved once changed. Pretty much reverts back to default once the settings screen is exited or any other setting is changed .
