### ISSUE TITLE
Can't change wallpaper change source

### ISSUE THREAD

**Issue by blindmodz** [you-apps/WallYou#191]
### Steps to reproduce

1. Go to settings.
2. Change wallpaper changer source to Favorites.

### Expected behavior

Should change source from Wallhaven to Favorites and stay there.

### Actual behavior

Change back from Favorites to Wallhaven after closed the app.

### Wall You version

8.0

### Android version

Android 13 (MIUI14) 

### Other details

This issued wasn't there in previous version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/you-apps/WallYou/issues/184

**Comment by Bnyro** [comment]
https://github.com/you-apps/WallYou/releases/tag/v0.8.1
