### ISSUE TITLE
The 8.1 tag is wrong.

### ISSUE THREAD

**Issue by linsui** [you-apps/WallYou#193]
### Steps to reproduce

See the tag.

### Expected behavior

It should be v8.1

### Actual behavior

It's v0.8.1.

### Wall You version

8.1

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed, thanks.

**Comment by linsui** [comment]
Thanks!
