### ISSUE TITLE
Can't export favorites (Serialization Error)

### ISSUE THREAD

**Issue by im-trisha** [you-apps/WallYou#194]
### Steps to reproduce

1. Install the app
2. Put some wallhaven wallpapers into favorites
3. Try to export your favorites into /storage/emulated/0/Backups (Probably the folder isn't important)

### Expected behavior

I should get a json file with the exported settings

### Actual behavior

I got a serialization error.
![Here's the screenshot](https://github.com/you-apps/WallYou/assets/68499230/c1594d9f-cfd6-4acf-adef-ee6706bd28f7)

### Wall You version

8.1 (26)

### Android version

Android 14. crDroid 10.4

### Other details

Hello.

I started using Wall You not too long ago, and I'm loving it. When I tried backing up the favorites I got a serialization error. I hope its not that hard of a fix! Or maybe its just a personal phone problem? I tried cleaning the cache but that didn't work.

I also hope the Issue i filed is good. Please tell me if you need more details.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Will be fixed with the next release.

**Comment by im-trisha** [comment]
Perfect! Were you able to reproduce the issue? :)

**Comment by Bnyro** [comment]
Yes 👍
