### ISSUE TITLE
Add random wallpapers (QS) to favorites

### ISSUE THREAD

**Issue by im-trisha** [you-apps/WallYou#195]
### Describe your suggested feature

Hello, its me, again, I hope not to bother you!

I discovered the "Random wallpaper" quick settings a few days ago, and after pressing it a few times, I got some cool wallpapers, but to save them I had to manually search them in the app for a few minutes. 

I have the "Add to favorites when applying" enabled, so i thought it could be added automatically in this case

Or even better, making an "Applied wallpapers" history, so that the applied wallpapers can be "saved" without being put into the favorites (Like in this case). Please let me know what you think!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sounds reasonable, it will automatically add the applied images to favorites in the future if you have the preference you mentioned enabled :+1:

**Comment by im-trisha** [comment]
Sounds wonderful! If I ever manage to do a PR, would you consider to add the history panel?

**Comment by Bnyro** [comment]
> If I ever manage to do a PR, would you consider to add the history panel?
>
Yes, sounds good :+1:

**Comment by Bnyro** [comment]
I've created an issue about it because I've applied a random wallpaper and can't find it anymore, so this is certainly a good idea (and will make the add to favorites when applying option unnecessary for random wallpapers).

see https://github.com/you-apps/WallYou/issues/199.
