### ISSUE TITLE
help for stupid ass people like me

### ISSUE THREAD

**Issue by Vansmak** [you-apps/WallYou#203]
### Describe your suggested feature

How does this work? I see in issues that adding local folders was deed bet I don't see that option. I see a favorites section as well but how do I tell the app to use those for the changer? Seems I can only choose the built in sources? Help an old dumb person please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That only works for the automatic wallpaper changer: Settings -> scroll down a bit -> Wallpaper changer source -> local -> choose a folder.
