### ISSUE TITLE
Wallhaven causing repeated EOF toast notification - No images load

### ISSUE THREAD

**Issue by twizzlebizzle** [you-apps/WallYou#204]
### Steps to reproduce

1. Open app.  
2. Wallhaven doesn't load any images and a toast notification keeps showing up.
3. If I move sources its okay

### Expected behavior

Load Wallhaven images

### Actual behavior

Doesn't load them and has an annoying toast notification.

### Wall You version

8.1

### Android version

android 14.

### Other details

![Screenshot_20240708-184938](https://github.com/you-apps/WallYou/assets/11423542/14c9a364-304d-45cc-bb2e-6d0182177284)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See https://bsky.app/profile/wallhaven.bsky.social
