### ISSUE TITLE
Opacity or darkness effect

### ISSUE THREAD

**Issue by contact-maximux** [you-apps/WallYou#205]
### Describe your suggested feature

I came from reddit wallpaper changer. Now your app is just sea against it. 
Thanks for giving us wonderful app. I could not think of what you guys have made. 

One problem I am facing. Readability of font over wallpaper. There should an option to darken or opacity change so that any text over wallpaper is easily readable. Please refer this app https://play.google.com/store/apps/details?id=com.bryanwalsh.redditwallpaper2

It is doing this job very very perfectly.
![one](https://github.com/user-attachments/assets/c1606d92-6a37-43ad-a69b-b064c17d76fe)
![two](https://github.com/user-attachments/assets/273d3466-1ba6-4dfd-b56d-fc88a8134df5)

Please implement without this effect, It is very hard to use any wallpaper. Mention effect should be applicable in auto wallpaper change settings. @Bnyro @Atrafon @Ilithy 

Thanks once again for wonderful app @yo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Closed due to unrespectful behavior (pinging people)
