### ISSUE TITLE
Image editing setting in Auto Wallpaper Mode to apply 

### ISSUE THREAD

**Issue by contact-maximux** [you-apps/WallYou#206]
### Describe your suggested feature

Best app, Thank you for this. 
I do have one request.
While applying AUTO WALLPAPER, please respect edit setting last used.

**Example: If I change the contrast or made image grayscale or something from edit button, then please add these effect to wallpaper being applied using AUTO WALLPAPER option.**

### Other details

I have created mockup, please see. its last in image 
<img width="600" alt="Screenshot_20240924-170915_Wall You" src="https://github.com/user-attachments/assets/af280aa5-a01d-4269-a996-6a59e74cf094">

And it will apply below effects in auto wallpaper mode.
![Screenshot_20240924-171946_Wall You](https://github.com/user-attachments/assets/6d6e1366-653b-430a-8c16-2e66193e2b17)

**In other case you can be devise your way.I opt minimal UI change**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The "Apply image filters" preference does exactly what you described.
