### ISSUE TITLE
random Wallpaper and Automatic Switcher not working with Reddit.

### ISSUE THREAD

**Issue by haldi4803** [you-apps/WallYou#208]
### Steps to reproduce

Change automatic Wallpaper Switcher to Reddit.
Change Reddit to r/MobileWallpaper
Wait 15 minutes or press QuickTile "Random Wallpaper"

### Expected behavior

If you select Wallhaven as Source it works fine.

### Actual behavior

Not changing Wallpapers.

### Wall You version

8.1(26)

### Android version

Android 14

### Other details
Manually selecting a Wallpaper in the app and applying works!

Syslog
[2024-10-12_07.48.zip](https://github.com/user-attachments/files/17348945/2024-10-12_07.48.zip)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by haldi4803** [comment]
[2024-10-20_16.06.zip](https://github.com/user-attachments/files/17450539/2024-10-20_16.06.zip)
No changes in 9.0

**Comment by haldi4803** [comment]
This was supposed to be fixed in 9.1 right?

**Comment by Bnyro** [comment]
No, it's not yet released.
