### ISSUE TITLE
Crashes when choosing wallpaper source

### ISSUE THREAD

**Issue by don-dolarson** [you-apps/WallYou#210]
### Steps to reproduce

Open the app
Go to settings, wallpaper changer source > online
Choose source

### Expected behavior

Not crashing

### Actual behavior

App just closes without applying any change.

### Wall You version

9.0

### Android version

Android 13

### Other details

Just updated from previous release which worked as expected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There've been some internal changes and thus the old configuration format of the wallpaper options is no longer compatible.

The next update will just reset the configuration and everything will work again as usual, you must however redo the wallpaper changer configuration unfortunately.
