### ISSUE TITLE
NASA APOD support

### ISSUE THREAD

**Issue by CPU0NRD** [you-apps/WallYou#212]
### Describe your suggested feature

Every day, NASA chooses an astronomy-related picture to showcase. API keys to obtain these images are free and easy to access. It would be nice to see APOD as a source option to choose from.

### Other details

APOD occasionally do not showcase an image, but a video instead. The app would need to be able to distinguish between a video link and an image when it is refreshed. Trial api key is also rate limited and image resolution varies wildly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Ref https://api.nasa.gov/
