### ISSUE TITLE
Spotlight wallpapers are not sorted by date

### ISSUE THREAD

**Issue by UlyssesZh** [you-apps/WallYou#213]
### Steps to reproduce

Open Spotlight tab.

### Expected behavior

The wallpapers are sorted by descending date, like Bing.

### Actual behavior

The most recent wallpaper is not at the top, and the wallpapers shown are random every time the tab is opened.

### Wall You version

9.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Feel free to create a pull request to modify the usage of their API.

I haven't found any info about how to sort the results in my research, and thus don't plan to change that.
