### ISSUE TITLE
Screen on/off as interval

### ISSUE THREAD

**Issue by SCHOUTER** [you-apps/WallYou#218]
### Describe your suggested feature

Would be nice to have something like: Everytime the screen gets activtated, the background is different. So you could cycle through the pictures much faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's technically impossible without Root permissions, see https://stackoverflow.com/questions/11346958/listening-for-action-screen-off.
